<?php
  $values = [
    'home' => 'Home',
    'about_us' => 'About Us',
    'cost' => 'Cost',
    'contact' => 'Contact',
    'start' => 'Start',
    'home_p' => 'Unlimited internet solution without limits.',
    'featured_service_h1' => 'Stable Network',
    'featured_service_p1' => 'Very suitable for those of you who like playing games or live streaming.',
    'featured_service_h2' => 'Affordable Rates',
    'featured_service_p2' => 'The rates we set are very friendly.',
    'featured_service_h3' => 'Free Maintenance',
    'featured_service_p3' => 'We will repair any damage without any charge.',
    'featured_service_h4' => 'Cheap Installation Cost',
    'featured_service_p4' => 'Our installation costs are quite friendly, starting from IDR 300,000 (depending on domicile).',
    'about_us_p' => '<b>PT. Azkyal Network Madina</b> is engaged in the field of internet service providers. We strive to provide quality internet services and will continue to update according to the development of the digital era.',
    'our_superiority' => 'Our Superiority',
    'our_superiority_p' => 'We always prioritize customer comfort.',
    'our_superiority_1' => 'Quick installation',
    'our_superiority_2' => 'Repairs will be expedited',
    'our_superiority_3' => 'Free repair and replacement of tools',
    'our_superiority_p2' => 'Don\'t hesitate to join us!',
    'private_user' => 'Private Customer',
    'ap_voucher' => 'AP Voucher',
    'admin_support' => 'Admin Support',
    'number_of_technicians' => 'Number of Technicians',
    'monthly_prices_h' => 'Monthly Prices',
    'monthly_prices_p' => 'The rates we set are very friendly and suitable even if you are still a student.',
    'package' => '=>package Package',
    'idr_cost' => 'IDR :cost',
    'start_subscribe' => 'Start Subscription',
    'package_benefit_1' => 'Stable price',
    'package_benefit_2' => 'Unlimited quota',
    'package_benefit_3' => 'Speed up to :speedmbps',
    'package_benefit_4' => 'Ideal for :device-count devices',
    'package_benefit_5' => 'Tools are loaned',
    'package_benefit_6' => 'Free installation fee (terms and conditions apply)',
    'package_benefit_7' => 'Suitable for smart tv.',
    'contact_p' => 'If there is anything unclear and you want to ask, please contact us.',
    'address' => 'Address',
    'contact_us' => 'Contact Us',
    'email_us' => 'Email Us',
    'additional_services' => 'Other Services',
    'additional_services_p' => 'We also provide other services that may interest you.',
    'cctv_installation' => 'CCTV Installation',
    'cctv_installation_p' => 'We provide CCTV installation services with rates starting from IDR 200,000 per point (costs excluding DVR).',
    'wifi_voucher' => 'Voucher WiFi',
    'wifi_voucher_p' => 'You can be our wifi voucher reseller. Access point installation fee starts from IDR 300,000. You will get one free voucher account.',
    'affiliated_with' => 'Affiliated With'
  ];
?>
VALUES['en-us'] = JSON.parse('<?=str_replace("'", "\\'", json_encode($values))?>');